-- local lspconfig = require'lspconfig'
-- local util = require'lspconfig/util'
--
-- local on_attach = function(client)
--     require'completion'.on_attach(client)
-- end

-- lspconfig.rust_analyzer.setup({
--     on_attach = on_attach,
--     root_dir = util.root_pattern("Cargo.toml"),
--     settings = {
--         ["rust-analyzer"] = {
--             imports = {
--                 granularity = {
--                     group = "module",
--                 },
--                 prefix = "self",
--             },
--             cargo = {
--                 allFeatures = true,
--                 buildScripts = {
--                     enable = true,
--                 },
--             },
--             procMacro = {
--                 enable = true
--             },
--         }
--     }
-- })
--
