[general]
live_config_reload = true

[colors.primary]
background = "#000000"
foreground = "#c5c8c6"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font Propo"
style = "Regular"

[terminal.shell]
args = ["--login", "-c", "sleep 0.1 && zellij attach zmain --create"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
opacity = 1.0
option_as_alt = "Both"

[window.padding]
x = 3
y = 0
